const data = [
    {
        name: "Counter-Strike 2",
        genres: ["First-Person Shooter"],
        price: "Free",
        multiplayer: true,
        dlc: false,
    },
    {
        name: "Cuphead",
        genres: ["Platformer", "Shooter"],
        multiplayer: true,
        price: "$19.99",
        dlc: true,
    },
    {
        name: "Fortnite",
        genres: ["Battle Royale", "Shooter"],
        multiplayer: true,
        price: "Free",
        dlc: false,
    },
    {
        name: "One Piece: Odyssey",
        genres: ["Open-World", "RPG", "Anime"],
        multiplayer: false,
        price: "$59.99",
        dlc: true,
    },
    {
        name: "Genshin Impact",
        genres: ["Open-World", "RPG", "Gacha"],
        multiplayer: true,
        price: "Free",
        dlc: false,
    },
    {
        name: "Minecraft",
        genres: ["Open-World", "Adventure"],
        multiplayer: true,
        price: "$29.99",
        dlc: true,
    },
    {
        name: "Raft",
        genres: ["Open-World", "RPG", "Anime"],
        multiplayer: false,
        price: "$59.99",
        dlc: true,
    },
    {
        name: "Sea of Thieves",
        genres: ["Open-World", "RPG", "Anime"],
        multiplayer: false,
        price: "$59.99",
        dlc: true,
    },
];